backend:
  name: github
  repo: Jde-souza/dsh
  branch: main
  auth_type: pkce
  app_id: Ov23lir2ydF2887hv3Y7

local_backend: true

media_folder: "asset/img/blog"
public_folder: "asset/img/blog"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Fecha de publicación", name: "date", widget: "datetime"}
      - {label: "Imagen Destacada", name: "thumbnail", widget: "image", required: false}
      - {label: "Descripción Corta", name: "description", widget: "text"}
      - {label: "Cuerpo", name: "body", widget: "markdown"}
      - {label: "Autor", name: "author", widget: "string", default: "DSH Team"}
      - {label: "Categoría", name: "category", widget: "select", options: ["Entretenimiento", "Accesibilidad", "Eventos", "Tecnología", "Noticias"], default: "Entretenimiento"}
